### ISSUE TITLE
DebugOptionsListeners should be registered with different properties

### ISSUE THREAD

**Issue by stbischof** [eclipse-equinox/equinox.framework#16]
`ModuleContainer` and `Debug ( from EquinoxContainer)` are both registered as an `DebugOptionsListeners`,but with the same Property
`"listener.symbolic.name"="org.eclipse.osgi"`

https://github.com/eclipse-equinox/equinox.framework/blob/3d60fea55492b2e2239c21f6bec865f87a8852ed/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/SystemBundleActivator.java#L129-L133

They should have different `listener.symbolic.name` or an additional ServiceProperty that helps to filter them.

**Comment by tjwatson** [comment]
Who would filter them besides the implementation of FrameworkDebugOptions?  That property is used by `org.eclipse.osgi.internal.debug.FrameworkDebugOptions.optionsChanged(String)` so that any changes to "org.eclipse.osgi" trace options notify the two DebugOptionsListener instances.  We cannot simply change these two to use different trace option prefix without changing the contents of the `.options` file for the different trace options in the framework.

**Comment by stbischof** [comment]
Thank you for explaining.
