### ISSUE TITLE
SignedBundleTest fails when run on Java 18

### ISSUE THREAD

**Issue by akurtakov** [eclipse-equinox/equinox.framework#25]
Cases "SHA1withDSA" and "SHA1withRSA" fail (https://download.eclipse.org/eclipse/downloads/drops4/I20220331-1800/testresults/html/org.eclipse.osgi.tests_ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18.html) due to Java 18 treating SHA1 as unsigned (https://bugs.openjdk.java.net/browse/JDK-8269039) . 
The following would fix it but it uses Java 11 API. @tjwatson  Is there a reason to keep this bundle at Java 8 still?
``` java
		// Java 18 treats SHA1 signed artifacts as unsigned
		if (Runtime.version().feature() < 18) {
			doTestBug378155("SHA1withDSA");
			doTestBug378155("SHA1withRSA");
		}
```

Thinking more about it if latest Java treats SHA1 as unsigned maybe we should remove these tests in general on every version.

**Comment by tjwatson** [comment]
> Thinking more about it if latest Java treats SHA1 as unsigned maybe we should remove these tests in general on every version.

I was slow to get my comment in issue #23.  I figured we should simply remove the SHA1 tests because they have been deemed insecure anyway.  As for keeping the tests on Java 8, I don't have issues moving up.  The `org.eclipse.core.tests.harness` has already moved up to Java 11.  I simply cannot have `org.eclipse.osgi` move off Java 8 for a while yet.  But the time I can move `org.eclipse.osgi` off of Java 8 the current LTS version will probably be already out of service and I'll move all the way up to Java 21.

I'll remove these SHA1 cases as part of #23.  Closing this issue as it is a dup.
